### ISSUE TITLE
Turn this in to a Preference Pack (glassdesignstudio)

### ISSUE THREAD

**Issue by luzpaz** [glassondesignstudio/GdsLightBlue#1]
...so users can install this via the addon manager.  
Documentation:  
https://wiki.freecad.org/Preference_Packs  
https://github.com/FreeCAD/FreeCAD-addons/issues/201

**Comment by glassondesignstudio** [comment]
Thanks for the suggestion. That's a good idea, and I will follow up on it when the theme has undergone more testing.

**Comment by luzpaz** [comment]
@glassondesignstudio any traction on this?

**Comment by glassondesignstudio** [comment]
Yes and no. I've done some more work on the stylesheet itself in the development branch but haven't done anything about a preference pack. I didn't read the documentation properly when you first raised the issue but it looks to be relatively straightforward so I will start working on it. 

TBH it's not my highest priority but I'll work on it as much as my day jobs allow.

**Comment by glassondesignstudio** [comment]
@luzpaz I have just committed a basic preference pack for my stylesheet. The stylesheet will be a work in progress for some time but I will be addressing issues with it as I come across them. The master branch of the repo has the latest version of the preference pack.

**Comment by luzpaz** [comment]
@glassondesignstudio, now you can add this to the addon manager and update changes as you see fit. Those changes will propagate everytime a user updates your preference pack in the addon manager. That way you can receive feedback and even patches (if you so wish)?
