### ISSUE TITLE
Rename stylesheet so is less generic

### ISSUE THREAD

**Issue by luzpaz** [glassondesignstudio/GdsLightBlue#4]
`FreeCAD-stylesheet` does not distinguish itself. Perhaps a more unique name ?

**Comment by glassondesignstudio** [comment]
It does to me lol. You're right though it is a pretty poor name and I am considering changing it. The stylesheet is a fork of FreeCAD's LightBlue stylesheet and the stylesheet identifies itself as GdsLightBlue so I thought I might go with that. Do you have any suggestions?

**Comment by luzpaz** [comment]
'GDSLightBlue' ?

**Comment by glassondesignstudio** [comment]
The preference pack has been renamed to GdsLightBlue
